[project]
name = 'Decentralized-Noise-Pollution-Monitoring'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.mitigation-tracking]
path = 'contracts/mitigation-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.sensor-network]
path = 'contracts/sensor-network.clar'
clarity_version = 2
epoch = 2.5

[contracts.source-attribution]
path = 'contracts/source-attribution.clar'
clarity_version = 2
epoch = 2.5

[contracts.threshold-violation]
path = 'contracts/threshold-violation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
